# Projects, Products, and Contacts {-}

Contacts, projects, and products share a relationship in mdEditor and are each entered independently.

## Projects {-}
A project encompasses a discrete effort on a particular topic with defined goals or objectives. As an interim goal, target projects to undergo data management are science projects whose topics and resulting products have value to partners or the public being able to discover, access, and potentially use them. 

## Products {-}
A product is a resource, usually (but not necessarily) developed as an output from a project. Products (aka Data Resources) are defined as recorded information and can be generated by experiments, models, simulations and observations. Not every output of a project is necessarily a product, however. For example, meeting minutes do not have standalone value as a publicly-available resource. Products that receive metadata records are at the discretion of the principal investigator, their supervisor and any relevant program or branch policies but should be guided by the principle of reuse (i.e., if there is an intent that a tabular dataset can be used again, it should be a product that undergoes data management; for reports, they should be managed to be discoverable and associated with the datasets and code used to produce results). Consider carefully why a product would remain in the project file but NOT undergo data management. This should be a rare occurrence.

## Contacts {-}
Contacts are the individuals and organizations involved with projects and products (e.g., collaborators, funders). Contacts are entered once in mdEditor and can be added to multiple projects and products.
Consult the contacts section for information on maintaining the contacts record and adding contacts.

## Relationships {-}
Projects and products will always have a relationship with contacts. Contacts can be individuals or organization. Projects will always have at least one point of contact. Additional contact relationships may include project authors, metadata creators, funders, principal investigators, publishers, distributors, and many others. 
Contact types are specified in the contact record (examples: federal, state, NGO). Specific roles for each contact are defined within the respective project and product records (examples: principal investigator, collaborator).
Products are often the results of projects. mdEditor defines the relationships between projects and products through the Associated tab.
